-- 0001_core_schema.sql — Connectum core schema (shared-workspace MVP)
-- RLS: any authenticated team member may access everything (single workspace).

create extension if not exists "uuid-ossp";

-- Helper: shared-workspace access = authenticated
create or replace function public.is_team_member() returns boolean
language sql stable as $$ select auth.role() = 'authenticated' $$;

-- Team profile (1:1 with auth.users)
create table public.team_member (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Connected source accounts (token/secret bodies live in Vault; here we keep refs)
create table public.supabase_account (
  id uuid primary key default uuid_generate_v4(),
  label text not null,
  access_token_ref text,           -- vault secret name
  refresh_token_ref text,          -- vault secret name
  expires_at timestamptz,
  created_at timestamptz not null default now()
);
create table public.amplitude_account (
  id uuid primary key default uuid_generate_v4(),
  label text not null,
  region text not null default 'us',
  api_key_ref text,
  secret_key_ref text,
  created_at timestamptz not null default now()
);
create table public.axiom_account (
  id uuid primary key default uuid_generate_v4(),
  label text not null,
  api_token_ref text,
  created_at timestamptz not null default now()
);

-- Services (1 service = 1 Supabase project)
create table public.service (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  supabase_account_id uuid references public.supabase_account(id) on delete set null,
  supabase_project_ref text,
  amplitude_account_id uuid references public.amplitude_account(id) on delete set null,
  axiom_account_id uuid references public.axiom_account(id) on delete set null,
  axiom_dataset text,
  join_key_config jsonb not null default '{"amplitude_user_id":"supabase.id"}'::jsonb,
  created_at timestamptz not null default now()
);
create table public.service_table (
  id uuid primary key default uuid_generate_v4(),
  service_id uuid not null references public.service(id) on delete cascade,
  source_schema text not null default 'public',
  source_table text not null,
  role text not null default 'related',          -- 'user_table' | 'related'
  column_map jsonb not null default '{}'::jsonb,  -- {user_id, email, ...}
  cursor_column text default 'updated_at'
);

-- Mirrored data
create table public.crm_user (
  id uuid primary key default uuid_generate_v4(),
  service_id uuid not null references public.service(id) on delete cascade,
  source_user_id text not null,
  email text,
  display_name text,
  supabase_profile jsonb not null default '{}'::jsonb,
  amplitude_profile jsonb not null default '{}'::jsonb,
  contact_status text not null default 'not_contacted', -- 'not_contacted' | 'contacted'
  custom_fields jsonb not null default '{}'::jsonb,
  ai_summary text,
  ai_summary_generated_at timestamptz,
  ai_summary_input_hash text,
  axiom_signals jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (service_id, source_user_id)
);
create table public.crm_user_event (
  id bigint generated by default as identity primary key,
  crm_user_id uuid not null references public.crm_user(id) on delete cascade,
  event_type text not null,
  event_time timestamptz not null,
  platform text, os text, browser text,
  props jsonb not null default '{}'::jsonb
);
create index on public.crm_user_event (crm_user_id, event_time desc);

create table public.mirrored_row (
  id uuid primary key default uuid_generate_v4(),
  service_id uuid not null references public.service(id) on delete cascade,
  service_table_id uuid not null references public.service_table(id) on delete cascade,
  source_pk text not null,
  data jsonb not null default '{}'::jsonb,
  linked_crm_user_id uuid references public.crm_user(id) on delete set null,
  unique (service_table_id, source_pk)
);

-- Manual operational layer
create table public.custom_field (
  id uuid primary key default uuid_generate_v4(),
  scope text not null default 'workspace',   -- 'workspace' | 'service'
  service_id uuid references public.service(id) on delete cascade,
  name text not null,
  type text not null,                        -- text|select|multi_select|date|checkbox|url|number|person
  options jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table public.page_block (
  id uuid primary key default uuid_generate_v4(),
  crm_user_id uuid not null references public.crm_user(id) on delete cascade,
  position double precision not null default 0,
  type text not null,                        -- channel_record|text|heading|image|divider|field_ref
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.history_entry (
  id uuid primary key default uuid_generate_v4(),
  crm_user_id uuid not null references public.crm_user(id) on delete cascade,
  entry_date date not null,
  image_url text,
  memo text,
  position double precision not null default 0,
  created_at timestamptz not null default now()
);

-- Views / sync state
create table public.view (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  scope text not null default 'workspace',
  service_id uuid references public.service(id) on delete cascade,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table public.sync_run (
  id uuid primary key default uuid_generate_v4(),
  service_id uuid references public.service(id) on delete cascade,
  source text not null,                      -- supabase|amplitude|axiom
  status text not null default 'running',    -- running|success|error
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  stats jsonb not null default '{}'::jsonb,
  error text
);
create table public.sync_cursor (
  id uuid primary key default uuid_generate_v4(),
  service_id uuid not null references public.service(id) on delete cascade,
  source text not null,
  scope_key text not null,
  cursor_value text,
  updated_at timestamptz not null default now(),
  unique (service_id, source, scope_key)
);

-- Enable RLS + shared-workspace policies on every public table
do $$
declare t text;
begin
  for t in
    select tablename from pg_tables
    where schemaname = 'public'
      and tablename in (
        'team_member','supabase_account','amplitude_account','axiom_account',
        'service','service_table','crm_user','crm_user_event','mirrored_row',
        'custom_field','page_block','history_entry','view','sync_run','sync_cursor')
  loop
    execute format('alter table public.%I enable row level security;', t);
    execute format($p$create policy "team_all" on public.%I
      for all to authenticated using (public.is_team_member()) with check (public.is_team_member());$p$, t);
  end loop;
end $$;
